### ISSUE TITLE
hi. A small suggestion, refactor the client UI part by modern packaging

### ISSUE THREAD

**Issue by loycoder** [SnapDrop/snapdrop#641]
snapdrop works well, but is there any official consideration of refactoring the UI part of the client, for example: react+ts+vite? It's 2024, after all

**Comment by RobinLinus** [comment]
For such a simple tool, it's complete overkill to use heavy frameworks which are intended for large projects managed by large teams.

**Comment by AlexDev404** [comment]
@RobinLinus I'd say that even so, using something as simple as EJS would make things easier to work with and for developers to contribute, since although static HTML is all fine and okay, it makes things harder to work with.

Plus, there are many compilers for it too, and allows it to be converted back into optimized HTML for the web.
